#!/usr/bin/env ruby 

require 'highline/import'

require './src/setup.rb'
require './src/password_crypt.rb'

if ARGV.flags.keyfile?
  keyfile = ARGV.flags.keyfile;
else
  keyfile = DEFAULT_KEY_FILE
end

pc = PasswordCrypt.new keyfile, ARGV.flags.case_sensitive

if ARGV.flags.lookup?
  output = pc.lookup ARGV.flags.lookup 
else
  password = ask("Enter password: ") { |q| q.echo = '*' }

  output = pc.lookup password
end

puts output
