#!/usr/bin/env ruby 

require 'highline/import'

require './src/setup.rb'
require './src/password_crypt.rb'

pc = PasswordCrypt.new({ :filename => ARGV.flags.keyfile, :case_sensitive => ARGV.flags.case_sensitive })

if ARGV.flags.lookup?
  output = pc.lookup ARGV.flags.lookup 
else
  password = ask("Enter password: ") { |q| q.echo = '*' }

  output = pc.lookup password
end

puts output
