#!/usr/bin/env ruby 

require 'highline/import'

require './setup.rb'

if ARGV.flags.keyfile?
  file = ARGV.flags.keyfile;
else
  file = DEFAULT_KEY_FILE
end

@key = YAML::load(File.open(file)); 

def lookup(input)
  input.split('').map do |char|
    if @key.has_key? char
      @key[char]
    else
      char
    end
  end.join
end

if ARGV.flags.lookup?
  output = lookup ARGV.flags.lookup 
else
  password = ask("Enter password: ") { |q| q.echo = '*' }

  output = lookup password
end

puts output
